"""AC-10: the LangChain MCP adapter loads the custom ``pa`` server's tools and
resources over a real stdio subprocess (no mocking the adapter), a loaded tool
round-trips a real lookup, and a live Gemini agent drives at least one MCP tool
call (``@slow``, needs ``GEMINI_API_KEY``).

Machine-readable evidence: ``traces/mcp_tool_calls.jsonl`` (from the non-slow
round-trip test). Narrative evidence: ``traces/mcp_toolcall_transcript.md``
(regenerated by the slow test; a representative copy is committed).
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import pytest
from langchain_core.tools import BaseTool

from pa_copilot.config import load_settings
from pa_copilot.mcp_client import (
    build_client,
    load_pa_tools,
    load_policy,
    load_policy_dict,
    pa_session,
)
from pa_copilot.mcp_server import data_access

pytestmark = pytest.mark.asyncio


async def test_ac10_adapter_loads_mcp_tools_as_langchain_tools():
    tools = await load_pa_tools()
    by_name = {t.name: t for t in tools}
    assert isinstance(by_name["criteria_check"], BaseTool)
    assert {"benefit_lookup", "provider_lookup", "criteria_check"} <= set(by_name)


async def test_ac10_loaded_tool_round_trips_through_adapter():
    tools = {t.name: t for t in await load_pa_tools()}
    result = await tools["criteria_check"].ainvoke(
        {"service_code": "72148", "diagnosis_codes": ["M54.16"]}
    )
    payload = json.loads(result) if isinstance(result, str) else result
    assert payload["policy_id"] == "PA-MRI-LUMBAR"

    # record a structured tool-call line as evidence (byte-stable: overwrite, not append)
    log = Path(load_settings(env_file=None).traces_dir) / "mcp_tool_calls.jsonl"
    entry = {
        "via": "langchain-mcp-adapters",
        "tool": "criteria_check",
        "args": {"service_code": "72148", "diagnosis_codes": ["M54.16"]},
        "result_status": payload["status"],
    }
    log.write_text(json.dumps(entry) + "\n", encoding="utf-8", newline="\n")


async def test_ac10_resource_read_through_adapter():
    text = await load_policy("PA-EGD")
    assert "43239" in text


async def test_ac10_capability_report_lists_tools_and_resources():
    from pa_copilot.mcp_client import capability_report

    report = await capability_report()
    assert isinstance(report, dict)
    assert "criteria_check" in report["tools"]
    assert "pa://criteria/index" in report["resources"]
    assert any("{policy_id}" in t for t in report["resource_templates"])


async def test_ac10_load_policy_dict_parses_the_json_body():
    policy = await load_policy_dict("PA-EGD")
    assert isinstance(policy, dict)
    assert policy["service_code"] == "43239"


async def test_ac10_session_path_round_trips_criteria_check():
    """I2: tools loaded against a held pa_session() bind to one long-lived
    subprocess and still round-trip a real lookup."""
    async with pa_session() as session:
        tools = {t.name: t for t in await load_pa_tools(session=session)}
        assert {"benefit_lookup", "provider_lookup", "criteria_check"} <= set(tools)
        result = await tools["criteria_check"].ainvoke(
            {"service_code": "72148", "diagnosis_codes": ["M54.16"]}
        )
        payload = json.loads(result) if isinstance(result, str) else result
        assert payload["policy_id"] == "PA-MRI-LUMBAR"


async def test_ac10_env_passthrough_redirects_server_corpora(tmp_path: Path):
    """I3: build_client(env=...) must reach the stdio subprocess so a test can
    point PA_SYNTHETIC_DIR at a stub corpus instead of the committed data."""
    stub = tmp_path / "syn"
    stub.mkdir()
    (stub / "benefits.json").write_text("{}", encoding="utf-8")
    (stub / "providers.json").write_text("{}", encoding="utf-8")
    (stub / "criteria.json").write_text(
        json.dumps(
            {
                "PA-STUB": {
                    "service_code": "STUB1",
                    "title": "Stub Policy",
                    "required_conditions": [{"id": "S-1", "text": "stub"}],
                    "exclusions": [],
                    "evidence_requirements": ["stub"],
                    "excluded_diagnoses": [],
                }
            }
        ),
        encoding="utf-8",
    )

    client = build_client(env={"PA_SYNTHETIC_DIR": str(stub)})
    tools = {t.name: t for t in await load_pa_tools(client=client)}

    hit = await tools["criteria_check"].ainvoke({"service_code": "STUB1"})
    hit = json.loads(hit) if isinstance(hit, str) else hit
    assert hit["policy_id"] == "PA-STUB"  # came from the stub, not production

    miss = await tools["criteria_check"].ainvoke({"service_code": "72148"})
    miss = json.loads(miss) if isinstance(miss, str) else miss
    assert miss["status"] == "not_found"  # production 72148 is invisible to the stub


async def test_ac10_default_client_still_sees_production_corpora():
    data_access.clear_corpora_cache()
    tools = {t.name: t for t in await load_pa_tools()}
    result = await tools["criteria_check"].ainvoke({"service_code": "72148"})
    payload = json.loads(result) if isinstance(result, str) else result
    assert payload["policy_id"] == "PA-MRI-LUMBAR"


async def test_ac10_medical_necessity_worker_invokes_real_criteria_check_in_graph():
    """AC-10 full in-graph evidence (Task 7): `build_medical_necessity_node` --
    the exact factory `graph.py` wires into the compiled StateGraph -- given
    REAL MCP tools loaded via `load_pa_tools(session=...)` (not a fake, per the
    task brief) actually dispatches `criteria_check` through the live `pa` MCP
    subprocess. Proven by capturing the ToolMessage the subprocess produced and
    asserting its content carries the real synthetic corpus's actual values
    (`policy_id`/`status`) -- something only the live server, not this test's
    fake LLM, could have put there -- rather than merely asserting the node
    didn't raise."""
    from langchain_core.messages import AIMessage

    from _fakes import FakeToolCallingModel, ai_tool_call
    from pa_copilot.agents.medical_necessity import build_medical_necessity_node
    from pa_copilot.schemas import BenefitResult, NecessityAssessment, PARequest

    captured_generations: list[list] = []

    class CapturingModel(FakeToolCallingModel):
        def _generate(self, messages, stop=None, run_manager=None, **kwargs):
            captured_generations.append(list(messages))
            return super()._generate(messages, stop=stop, run_manager=run_manager, **kwargs)

    request = PARequest(
        member_id="M100001", service_code="72148", diagnosis_codes=["M54.16"],
        requested_units=1, place_of_service="outpatient", provider_npi="1093817465",
        clinical_summary="MRI lumbar spine, 8 weeks PT, persistent radicular pain",
        missing_fields=[],
    )
    benefit = BenefitResult(
        covered=True, plan_id="PLAN-GOLD-PPO", requires_pa=True, network_status="in_network"
    )
    expected = NecessityAssessment(
        criteria_status="met", policy_id="PA-MRI-LUMBAR", citations=[], unmet_requirements=[],
        confidence=0.85, rationale="8 weeks PT + persistent radicular pain documented; not excluded",
    )
    model = CapturingModel(
        script=[
            ai_tool_call("criteria_check", {"service_code": "72148", "diagnosis_codes": ["M54.16"]}),
            AIMessage(content="assessed"),
        ],
        structured_responses=[expected],
    )

    async with pa_session() as session:
        tools = await load_pa_tools(session=session)
        node = build_medical_necessity_node(mcp_tools=tools, model=model)
        update = await node({"request": request, "benefit": benefit, "retrieved_criteria": []})

    assert update["necessity"] == expected

    tool_messages = [
        m for turn in captured_generations for m in turn if type(m).__name__ == "ToolMessage"
    ]
    assert tool_messages, "expected a ToolMessage from the real criteria_check MCP round trip"
    payloads = [
        json.loads(m.content) if isinstance(m.content, str) else m.content for m in tool_messages
    ]
    assert any(
        p.get("policy_id") == "PA-MRI-LUMBAR" and p.get("status") == "indeterminate" for p in payloads
    ), f"no ToolMessage carried the real corpus result: {payloads}"


@pytest.mark.slow
@pytest.mark.skipif(not os.environ.get("GEMINI_API_KEY"), reason="needs GEMINI_API_KEY")
async def test_ac10_gemini_agent_invokes_mcp_tool_transcript():
    from langchain.chat_models import init_chat_model

    s = load_settings(env_file=None)
    tools = await load_pa_tools()
    model = init_chat_model(
        f"google_genai:{s.model_agent}",
        temperature=s.temperature_agent,
        api_key=s.gemini_api_key,
    ).bind_tools(tools)

    msgs = [{"role": "user", "content": (
        "A provider requests prior auth for service 72148, diagnosis M54.16, member "
        "M100001. Use the available tools to check the benefit and the coverage criteria, "
        "then summarize what you found."
    )}]
    transcript = ["# MCP tool-call transcript (Gemini agent -> pa MCP server)\n"]
    by_name = {t.name: t for t in tools}

    for _ in range(4):
        ai = await model.ainvoke(msgs)
        msgs.append(ai)
        if not ai.tool_calls:
            transcript.append(f"\n## final answer\n\n{ai.content}\n")
            break
        for tc in ai.tool_calls:
            transcript.append(f"\n## tool call: `{tc['name']}`\n\n```json\n"
                              f"{json.dumps(tc['args'], indent=2)}\n```\n")
            obs = await by_name[tc["name"]].ainvoke(tc["args"])
            transcript.append(f"\n## tool result\n\n```json\n{obs}\n```\n")
            msgs.append({"role": "tool", "content": str(obs), "tool_call_id": tc["id"]})

    out = Path(load_settings(env_file=None).traces_dir) / "mcp_toolcall_transcript.md"
    out.write_text("".join(transcript), encoding="utf-8", newline="\n")

    body = out.read_text(encoding="utf-8")
    assert "tool call: `criteria_check`" in body or "tool call: `benefit_lookup`" in body
