"""AC-10: the LangChain MCP adapter loads the custom ``pa`` server's tools and
resources over a real stdio subprocess (no mocking the adapter), a loaded tool
round-trips a real lookup, and a live Gemini agent drives at least one MCP tool
call (``@slow``, needs ``GEMINI_API_KEY``).

Machine-readable evidence: ``traces/mcp_tool_calls.jsonl`` (from the non-slow
round-trip test). Narrative evidence: ``traces/mcp_toolcall_transcript.md``
(regenerated by the slow test; a representative copy is committed).
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import pytest
from langchain_core.tools import BaseTool

from pa_copilot.config import load_settings
from pa_copilot.mcp_client import load_pa_tools, load_policy

pytestmark = pytest.mark.asyncio


async def test_ac10_adapter_loads_mcp_tools_as_langchain_tools():
    tools = await load_pa_tools()
    by_name = {t.name: t for t in tools}
    assert isinstance(by_name["criteria_check"], BaseTool)
    assert {"benefit_lookup", "provider_lookup", "criteria_check"} <= set(by_name)


async def test_ac10_loaded_tool_round_trips_through_adapter():
    tools = {t.name: t for t in await load_pa_tools()}
    result = await tools["criteria_check"].ainvoke(
        {"service_code": "72148", "diagnosis_codes": ["M54.16"]}
    )
    payload = json.loads(result) if isinstance(result, str) else result
    assert payload["policy_id"] == "PA-MRI-LUMBAR"

    # record a structured tool-call line as evidence (byte-stable: overwrite, not append)
    log = Path(load_settings(env_file=None).traces_dir) / "mcp_tool_calls.jsonl"
    entry = {
        "via": "langchain-mcp-adapters",
        "tool": "criteria_check",
        "args": {"service_code": "72148", "diagnosis_codes": ["M54.16"]},
        "result_status": payload["status"],
    }
    log.write_text(json.dumps(entry) + "\n", encoding="utf-8", newline="\n")


async def test_ac10_resource_read_through_adapter():
    text = await load_policy("PA-EGD")
    assert "43239" in text


async def test_ac10_capability_report_lists_tools():
    from pa_copilot.mcp_client import capability_report

    report = await capability_report()
    assert isinstance(report, dict)
    assert "tools" in report
    assert "criteria_check" in report["tools"]


@pytest.mark.slow
@pytest.mark.skipif(not os.environ.get("GEMINI_API_KEY"), reason="needs GEMINI_API_KEY")
async def test_ac10_gemini_agent_invokes_mcp_tool_transcript():
    from langchain.chat_models import init_chat_model

    s = load_settings(env_file=None)
    tools = await load_pa_tools()
    model = init_chat_model(
        f"google_genai:{s.model_agent}",
        temperature=s.temperature_agent,
        api_key=s.gemini_api_key,
    ).bind_tools(tools)

    msgs = [{"role": "user", "content": (
        "A provider requests prior auth for service 72148, diagnosis M54.16, member "
        "M100001. Use the available tools to check the benefit and the coverage criteria, "
        "then summarize what you found."
    )}]
    transcript = ["# MCP tool-call transcript (Gemini agent -> pa MCP server)\n"]
    by_name = {t.name: t for t in tools}

    for _ in range(4):
        ai = await model.ainvoke(msgs)
        msgs.append(ai)
        if not ai.tool_calls:
            transcript.append(f"\n## final answer\n\n{ai.content}\n")
            break
        for tc in ai.tool_calls:
            transcript.append(f"\n## tool call: `{tc['name']}`\n\n```json\n"
                              f"{json.dumps(tc['args'], indent=2)}\n```\n")
            obs = await by_name[tc["name"]].ainvoke(tc["args"])
            transcript.append(f"\n## tool result\n\n```json\n{obs}\n```\n")
            msgs.append({"role": "tool", "content": str(obs), "tool_call_id": tc["id"]})

    out = Path(load_settings(env_file=None).traces_dir) / "mcp_toolcall_transcript.md"
    out.write_text("".join(transcript), encoding="utf-8", newline="\n")

    body = out.read_text(encoding="utf-8")
    assert "tool call: `criteria_check`" in body or "tool call: `benefit_lookup`" in body
