"""Regenerate ``traces/agentic_rag_decision.md`` — the AC-11 decision evidence.

Run from the repo root:

    python scripts/agentic_rag_demo.py

Shows the agentic-RAG decision both ways: an ``indeterminate`` criteria check
opens the retrieval tool inside the loop, an ``excluded`` one does not. The
document is byte-stable (no timestamps); real-model cosine scores are stable to
two decimals, which is all the doc prints.

``sys.path[0]`` is ``scripts/`` when invoked this way, so put the repo root on the
path first (Ruling R3).
"""

from __future__ import annotations

import sys
import tempfile
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_REPO_ROOT))
sys.path.insert(0, str(_REPO_ROOT / "src"))

from pa_copilot.config import get_settings  # noqa: E402
from pa_copilot.mcp_server.data_access import criteria_check  # noqa: E402
from pa_copilot.rag import index as rag_index  # noqa: E402
from pa_copilot.rag.tool import (  # noqa: E402
    reset_tool_embedder,
    search_clinical_guidance,
    set_tool_embedder,
    should_search_guidance,
)

_PSG_QUERY = (
    "Is attended in-lab polysomnography medically necessary when a home sleep "
    "apnea test is available for suspected obstructive sleep apnea?"
)


def _embedder():
    """Real BgeEmbedder if the model loads, else the FakeEmbedder (R12 fallback)."""
    from pa_copilot.rag.embedder import BgeEmbedder

    e = BgeEmbedder(get_settings().embedding_model)
    try:
        e.embed_query("warmup")
        return e, "BAAI/bge-small-en-v1.5 (real sentence-transformers model)"
    except Exception:  # pragma: no cover - offline fallback
        sys.path.insert(0, str(_REPO_ROOT / "tests"))
        from _fakes import FakeEmbedder

        return FakeEmbedder(), "FakeEmbedder (crc32 bag-of-words — model unavailable)"


def _fmt_citations(cits: list[dict]) -> str:
    if not cits:
        return "_(no citations returned)_\n"
    lines = []
    for c in cits:
        lines.append(f"- **`{c['clause_id']}`** — {c['relevance']}")
        lines.append(f"  > {c['quote']}")
    return "\n".join(lines) + "\n"


def main() -> None:
    # ``ignore_cleanup_errors``: chromadb keeps a live handle on its sqlite / hnsw
    # files that Windows will not let ``rmtree`` unlink until the process exits
    # (see ``rag/index.py`` — same reason it never ``rmtree``s the store).
    with tempfile.TemporaryDirectory(
        prefix="agentic-rag-demo-", ignore_cleanup_errors=True
    ) as tmp:
        import os

        os.environ["PA_CHROMA_DIR"] = str(Path(tmp) / "chroma")
        get_settings.cache_clear()

        embedder, embedder_label = _embedder()
        rag_index.build_index(embedder=embedder, rebuild=True)
        set_tool_embedder(embedder)
        try:
            a = criteria_check(service_code="95810", diagnosis_codes=["G47.33"])
            gate_a = should_search_guidance(a["status"])
            citations_a = (
                search_clinical_guidance.invoke(
                    {"query": _PSG_QUERY, "service_code": "95810"}
                )
                if gate_a
                else []
            )

            b = criteria_check(service_code="72148", diagnosis_codes=["M54.5"])
            gate_b = should_search_guidance(b["status"])
        finally:
            reset_tool_embedder()

    doc = f"""# Agentic-RAG decision evidence (AC-11)

Retrieval over the clinical-guidance corpus is a tool the agent *decides* to
call, gated by `should_search_guidance(...)` — it is not a fixed pipeline stage.
Generated by `scripts/agentic_rag_demo.py`.

Embedder: {embedder_label}

## Case A — `psg_indeterminate` (service 95810, dx G47.33)

1. `criteria_check(service_code="95810", diagnosis_codes=["G47.33"])`
   → `status="{a['status']}"` (policy `{a['policy_id']}`) — mechanical check
   cannot verify the narrative conditions.
2. `should_search_guidance("{a['status']}")` → **{gate_a}**
3. `search_clinical_guidance({_PSG_QUERY!r}, service_code="95810")`
   → {len(citations_a)} citation(s):

{_fmt_citations(citations_a)}
## Case B — `mri_lumbar_excluded` (service 72148, dx M54.5)

1. `criteria_check(service_code="72148", diagnosis_codes=["M54.5"])`
   → `status="{b['status']}"` (policy `{b['policy_id']}`) — M54.5 is a documented
   exclusion, a mechanical deny signal.
2. `should_search_guidance("{b['status']}")` → **{gate_b}**
3. `search_clinical_guidance` is **not called** — no narrative interpretation needed.

---

retrieval is inside the agent loop (predicate-gated), not a fixed pipeline step — the full in-graph run is PR5.
"""

    out_path = _REPO_ROOT / "traces" / "agentic_rag_decision.md"
    out_path.write_text(doc, encoding="utf-8", newline="\n")
    print(f"wrote {out_path.relative_to(_REPO_ROOT).as_posix()}")
    print(f"  embedder      : {embedder_label}")
    print(f"  Case A gate   : should_search_guidance({a['status']!r}) -> {gate_a}")
    print(f"  Case A cites  : {len(citations_a)}")
    print(f"  Case B gate   : should_search_guidance({b['status']!r}) -> {gate_b} (RAG not called)")


if __name__ == "__main__":
    main()
